apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels: # these labels belong to deployment
    app: catalogue
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: catalogue
      tier: app
      project: roboshop
  template: # this is the pod definition
    metadata:
      labels:
        app: catalogue
        tier: app
        project: roboshop
    spec:
      containers:
      - name: catalogue
        image: "vinodkumarpaleti/catalogue:{{ .Values.deployment.imageVersion }}"
        resources:
          requests:
            cpu: "50m"
            memory: "68Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: catalogue